const breeds = [
	{key: 'Airedale Terrier',
	text: 'Airedale Terrier',
	value: 'Airedale Terrier',
	content: 'Airedale Terrier'},
	{key: 'Akita',
	text: 'Akita',
	value: 'Akita',
	content: 'Akita'},
	{key: 'Alaskan Malamute',
	text: 'Alaskan Malamute',
	value: 'Alaskan Malamute',
	content: 'Alaskan Malamute'},
	{key: 'American Bulldog',
	text: 'American Bulldog',
	value: 'American Bulldog',
	content: 'American Bulldog'},
	{key: 'American English Coonhound',
	text: 'American English Coonhound',
	value: 'American English Coonhound',
	content: 'American English Coonhound'},
	{key: 'American Eskimo Dog',
	text: 'American Eskimo Dog',
	value: 'American Eskimo Dog',
	content: 'American Eskimo Dog'},
	{key: 'American Pit Bull Terrier',
	text: 'American Pit Bull Terrier',
	value: 'American Pit Bull Terrier',
	content: 'American Pit Bull Terrier'},
	{key: 'American Staffordshire Terrier',
	text: 'American Staffordshire Terrier',
	value: 'American Staffordshire Terrier',
	content: 'American Staffordshire Terrier'},
	{key: 'Australian Cattle Dog',
	text: 'Australian Cattle Dog',
	value: 'Australian Cattle Dog',
	content: 'Australian Cattle Dog'},
	{key: 'Australian Shepherd',
	text: 'Australian Shepherd',
	value: 'Australian Shepherd',
	content: 'Australian Shepherd'},
	{key: 'Australian Terrier',
	text: 'Australian Terrier',
	value: 'Australian Terrier',
	content: 'Australian Terrier'},
	{key: 'Basenji',
	text: 'Basenji',
	value: 'Basenji',
	content: 'Basenji'},
	{key: 'Basset Hound',
	text: 'Basset Hound',
	value: 'Basset Hound',
	content: 'Basset Hound'},
	{key: 'Beagle',
	text: 'Beagle',
	value: 'Beagle',
	content: 'Beagle'},
	{key: 'Bearded Collie',
	text: 'Bearded Collie',
	value: 'Bearded Collie',
	content: 'Bearded Collie'},
	{key: 'Bernedoodle',
	text: 'Bernedoodle',
	value: 'Bernedoodle',
	content: 'Bernedoodle'},
	{key: 'Bernese Mountain Dog',
	text: 'Bernese Mountain Dog',
	value: 'Bernese Mountain Dog',
	content: 'Bernese Mountain Dog'},
	{key: 'Bichon Frise',
	text: 'Bichon Frise',
	value: 'Bichon Frise',
	content: 'Bichon Frise'},
	{key: 'Black and Tan Coonhound',
	text: 'Black and Tan Coonhound',
	value: 'Black and Tan Coonhound',
	content: 'Black and Tan Coonhound'},
	{key: 'Bloodhound',
	text: 'Bloodhound',
	value: 'Bloodhound',
	content: 'Bloodhound'},
	{key: 'Bluetick Coonhound',
	text: 'Bluetick Coonhound',
	value: 'Bluetick Coonhound',
	content: 'Bluetick Coonhound'},
	{key: 'Bolognese',
	text: 'Bolognese',
	value: 'Bolognese',
	content: 'Bolognese'},
	{key: 'Border Collie',
	text: 'Border Collie',
	value: 'Border Collie',
	content: 'Border Collie'},
	{key: 'Borzoi',
	text: 'Borzoi',
	value: 'Borzoi',
	content: 'Borzoi'},
	{key: 'Boston Terrier',
	text: 'Boston Terrier',
	value: 'Boston Terrier',
	content: 'Boston Terrier'},
	{key: 'Boxer',
	text: 'Boxer',
	value: 'Boxer',
	content: 'Boxer'},
	{key: 'Brittany',
	text: 'Brittany',
	value: 'Brittany',
	content: 'Brittany'},
	{key: 'Brussels Griffon',
	text: 'Brussels Griffon',
	value: 'Brussels Griffon',
	content: 'Brussels Griffon'},
	{key: 'Bull Terrier',
	text: 'Bull Terrier',
	value: 'Bull Terrier',
	content: 'Bull Terrier'},
	{key: 'Bullmastiff',
	text: 'Bullmastiff',
	value: 'Bullmastiff',
	content: 'Bullmastiff'},
	{key: 'Cairn Terrier',
	text: 'Cairn Terrier',
	value: 'Cairn Terrier',
	content: 'Cairn Terrier'},
	{key: 'Canaan Dog',
	text: 'Canaan Dog',
	value: 'Canaan Dog',
	content: 'Canaan Dog'},
	{key: 'Cane Corso',
	text: 'Cane Corso',
	value: 'Cane Corso',
	content: 'Cane Corso'},
	{key: 'Cardigan Welsh Corgi',
	text: 'Cardigan Welsh Corgi',
	value: 'Cardigan Welsh Corgi',
	content: 'Cardigan Welsh Corgi'},
	{key: 'Cavalier King Charles Spaniel',
	text: 'Cavalier King Charles Spaniel',
	value: 'Cavalier King Charles Spaniel',
	content: 'Cavalier King Charles Spaniel'},
	{key: 'Chesapeake Bay Retriever',
	text: 'Chesapeake Bay Retriever',
	value: 'Chesapeake Bay Retriever',
	content: 'Chesapeake Bay Retriever'},
	{key: 'Chihuahua',
	text: 'Chihuahua',
	value: 'Chihuahua',
	content: 'Chihuahua'},
	{key: 'Chinese Crested Dog',
	text: 'Chinese Crested Dog',
	value: 'Chinese Crested Dog',
	content: 'Chinese Crested Dog'},
	{key: 'Chow Chow',
	text: 'Chow Chow',
	value: 'Chow Chow',
	content: 'Chow Chow'},
	{key: 'Cockapoo',
	text: 'Cockapoo',
	value: 'Cockapoo',
	content: 'Cockapoo'},
	{key: 'Cocker Spaniel',
	text: 'Cocker Spaniel',
	value: 'Cocker Spaniel',
	content: 'Cocker Spaniel'},
	{key: 'Collie',
	text: 'Collie',
	value: 'Collie',
	content: 'Collie'},
	{key: 'Dachshund',
	text: 'Dachshund',
	value: 'Dachshund',
	content: 'Dachshund'},
	{key: 'Dalmation',
	text: 'Dalmation',
	value: 'Dalmation',
	content: 'Dalmation'},
	{key: 'Doberman Pinscher',
	text: 'Doberman Pinscher',
	value: 'Doberman Pinscher',
	content: 'Doberman Pinscher'},
	{key: 'Dogue de Bordeaux',
	text: 'Dogue de Bordeaux',
	value: 'Dogue de Bordeaux',
	content: 'Dogue de Bordeaux'},
	{key: 'English Bulldog',
	text: 'English Bulldog',
	value: 'English Bulldog',
	content: 'English Bulldog'},
	{key: 'English Foxhound',
	text: 'English Foxhound',
	value: 'English Foxhound',
	content: 'English Foxhound'},
	{key: 'English Mastiff',
	text: 'English Mastiff',
	value: 'English Mastiff',
	content: 'English Mastiff'},
	{key: 'Fox Terrier',
	text: 'Fox Terrier',
	value: 'Fox Terrier',
	content: 'Fox Terrier'},
	{key: 'French Bulldog',
	text: 'French Bulldog',
	value: 'French Bulldog',
	content: 'French Bulldog'},
	{key: 'German Shepherd',
	text: 'German Shepherd',
	value: 'German Shepherd',
	content: 'German Shepherd'},
	{key: 'German Shorthaired Pointer',
	text: 'German Shorthaired Pointer',
	value: 'German Shorthaired Pointer',
	content: 'German Shorthaired Pointer'},
	{key: 'Giant Schnauzer',
	text: 'Giant Schnauzer',
	value: 'Giant Schnauzer',
	content: 'Giant Schnauzer'},
	{key: 'Golden Retriever',
	text: 'Golden Retriever',
	value: 'Golden Retriever',
	content: 'Golden Retriever'},
	{key: 'Goldendoodle',
	text: 'Goldendoodle',
	value: 'Goldendoodle',
	content: 'Goldendoodle'},
	{key: 'Great Dane',
	text: 'Great Dane',
	value: 'Great Dane',
	content: 'Great Dane'},
	{key: 'Great Pyrenees',
	text: 'Great Pyrenees',
	value: 'Great Pyrenees',
	content: 'Great Pyrenees'},
	{key: 'Greater Swiss Mountain Dog',
	text: 'Greater Swiss Mountain Dog',
	value: 'Greater Swiss Mountain Dog',
	content: 'Greater Swiss Mountain Dog'},
	{key: 'Greyhound',
	text: 'Greyhound',
	value: 'Greyhound',
	content: 'Greyhound'},
	{key: 'Havanese',
	text: 'Havanese',
	value: 'Havanese',
	content: 'Havanese'},
	{key: 'Ibizan Hound',
	text: 'Ibizan Hound',
	value: 'Ibizan Hound',
	content: 'Ibizan Hound'},
	{key: 'Irish Setter',
	text: 'Irish Setter',
	value: 'Irish Setter',
	content: 'Irish Setter'},
	{key: 'Irish Terrier',
	text: 'Irish Terrier',
	value: 'Irish Terrier',
	content: 'Irish Terrier'},
	{key: 'Irish Water Spaniel',
	text: 'Irish Water Spaniel',
	value: 'Irish Water Spaniel',
	content: 'Irish Water Spaniel'},
	{key: 'Irish Wolfhound',
	text: 'Irish Wolfhound',
	value: 'Irish Wolfhound',
	content: 'Irish Wolfhound'},
	{key: 'Italian Greyhound',
	text: 'Italian Greyhound',
	value: 'Italian Greyhound',
	content: 'Italian Greyhound'},
	{key: 'Jack Russell Terrier',
	text: 'Jack Russell Terrier',
	value: 'Jack Russell Terrier',
	content: 'Jack Russell Terrier'},
	{key: 'Japanese Chin',
	text: 'Japanese Chin',
	value: 'Japanese Chin',
	content: 'Japanese Chin'},
	{key: 'Labradoodle',
	text: 'Labradoodle',
	value: 'Labradoodle',
	content: 'Labradoodle'},
	{key: 'Labrador Retriever',
	text: 'Labrador Retriever',
	value: 'Labrador Retriever',
	content: 'Labrador Retriever'},
	{key: 'Leonberger',
	text: 'Leonberger',
	value: 'Leonberger',
	content: 'Leonberger'},
	{key: 'Lhasa Apso',
	text: 'Lhasa Apso',
	value: 'Lhasa Apso',
	content: 'Lhasa Apso'},
	{key: 'Maltese',
	text: 'Maltese',
	value: 'Maltese',
	content: 'Maltese'},
	{key: 'Maltipoo',
	text: 'Maltipoo',
	value: 'Maltipoo',
	content: 'Maltipoo'},
	{key: 'Manchester Terrier',
	text: 'Manchester Terrier',
	value: 'Manchester Terrier',
	content: 'Manchester Terrier'},
	{key: 'Mastiff',
	text: 'Mastiff',
	value: 'Mastiff',
	content: 'Mastiff'},
	{key: 'Miniature Australian Shepherd',
	text: 'Miniature Australian Shepherd',
	value: 'Miniature Australian Shepherd',
	content: 'Miniature Australian Shepherd'},
	{key: 'Miniature Bull Terrier',
	text: 'Miniature Bull Terrier',
	value: 'Miniature Bull Terrier',
	content: 'Miniature Bull Terrier'},
	{key: 'Miniature Pinscher',
	text: 'Miniature Pinscher',
	value: 'Miniature Pinscher',
	content: 'Miniature Pinscher'},
	{key: 'Miniature Poodle',
	text: 'Miniature Poodle',
	value: 'Miniature Poodle',
	content: 'Miniature Poodle'},
	{key: 'Miniature Schnauzer',
	text: 'Miniature Schnauzer',
	value: 'Miniature Schnauzer',
	content: 'Miniature Schnauzer'},
	{key: 'Mutt',
	text: 'Mutt',
	value: 'Mutt',
	content: 'Mutt'},
	{key: 'Neapolitan Mastiff',
	text: 'Neapolitan Mastiff',
	value: 'Neapolitan Mastiff',
	content: 'Neapolitan Mastiff'},
	{key: 'Newfoundland',
	text: 'Newfoundland',
	value: 'Newfoundland',
	content: 'Newfoundland'},
	{key: 'Norfolk Terrier',
	text: 'Norfolk Terrier',
	value: 'Norfolk Terrier',
	content: 'Norfolk Terrier'},
	{key: 'Norwich Terrier',
	text: 'Norwich Terrier',
	value: 'Norwich Terrier',
	content: 'Norwich Terrier'},
	{key: 'Old English Sheepdog',
	text: 'Old English Sheepdog',
	value: 'Old English Sheepdog',
	content: 'Old English Sheepdog'},
	{key: 'Otterhound',
	text: 'Otterhound',
	value: 'Otterhound',
	content: 'Otterhound'},
	{key: 'Papillon',
	text: 'Papillon',
	value: 'Papillon',
	content: 'Papillon'},
	{key: 'Peekapoo',
	text: 'Peekapoo',
	value: 'Peekapoo',
	content: 'Peekapoo'},
	{key: 'Pekingese',
	text: 'Pekingese',
	value: 'Pekingese',
	content: 'Pekingese'},
	{key: 'Pembroke Welsh Corgi',
	text: 'Pembroke Welsh Corgi',
	value: 'Pembroke Welsh Corgi',
	content: 'Pembroke Welsh Corgi'},
	{key: 'Petit Basset Griffon Vandeen',
	text: 'Petit Basset Griffon Vandeen',
	value: 'Petit Basset Griffon Vandeen',
	content: 'Petit Basset Griffon Vandeen'},
	{key: 'Pointer',
	text: 'Pointer',
	value: 'Pointer',
	content: 'Pointer'},
	{key: 'Pomeranian',
	text: 'Pomeranian',
	value: 'Pomeranian',
	content: 'Pomeranian'},
	{key: 'Pomsky',
	text: 'Pomsky',
	value: 'Pomsky',
	content: 'Pomsky'},
	{key: 'Poodle',
	text: 'Poodle',
	value: 'Poodle',
	content: 'Poodle'},
	{key: 'Portuguese Water Dog',
	text: 'Portuguese Water Dog',
	value: 'Portuguese Water Dog',
	content: 'Portuguese Water Dog'},
	{key: 'Pug',
	text: 'Pug',
	value: 'Pug',
	content: 'Pug'},
	{key: 'Rat Terrier',
	text: 'Rat Terrier',
	value: 'Rat Terrier',
	content: 'Rat Terrier'},
	{key: 'Redbone Coonhound',
	text: 'Redbone Coonhound',
	value: 'Redbone Coonhound',
	content: 'Redbone Coonhound'},
	{key: 'Rhodesian Ridgeback',
	text: 'Rhodesian Ridgeback',
	value: 'Rhodesian Ridgeback',
	content: 'Rhodesian Ridgeback'},
	{key: 'Rottweiler',
	text: 'Rottweiler',
	value: 'Rottweiler',
	content: 'Rottweiler'},
	{key: 'Saint Bernard',
	text: 'Saint Bernard',
	value: 'Saint Bernard',
	content: 'Saint Bernard'},
	{key: 'Saluki',
	text: 'Saluki',
	value: 'Saluki',
	content: 'Saluki'},
	{key: 'Samoyed',
	text: 'Samoyed',
	value: 'Samoyed',
	content: 'Samoyed'},
	{key: 'Schnoodle',
	text: 'Schnoodle',
	value: 'Schnoodle',
	content: 'Schnoodle'},
	{key: 'Shar Pei',
	text: 'Shar Pei',
	value: 'Shar Pei',
	content: 'Shar Pei'},
	{key: 'Shetland Sheepdog',
	text: 'Shetland Sheepdog',
	value: 'Shetland Sheepdog',
	content: 'Shetland Sheepdog'},
	{key: 'Shiba Inu',
	text: 'Shiba Inu',
	value: 'Shiba Inu',
	content: 'Shiba Inu'},
	{key: 'Shih Tzu',
	text: 'Shih Tzu',
	value: 'Shih Tzu',
	content: 'Shih Tzu'},
	{key: 'Siberian Husky',
	text: 'Siberian Husky',
	value: 'Siberian Husky',
	content: 'Siberian Husky'},
	{key: 'Silky Terrier',
	text: 'Silky Terrier',
	value: 'Silky Terrier',
	content: 'Silky Terrier'},
	{key: 'Spanish Water Dog',
	text: 'Spanish Water Dog',
	value: 'Spanish Water Dog',
	content: 'Spanish Water Dog'},
	{key: 'Springer Spaniel',
	text: 'Springer Spaniel',
	value: 'Springer Spaniel',
	content: 'Springer Spaniel'},
	{key: 'Staffordshire Bull Terrier',
	text: 'Staffordshire Bull Terrier',
	value: 'Staffordshire Bull Terrier',
	content: 'Staffordshire Bull Terrier'},
	{key: 'Standard Schnauzer',
	text: 'Standard Schnauzer',
	value: 'Standard Schnauzer',
	content: 'Standard Schnauzer'},
	{key: 'Sussex Spaniel',
	text: 'Sussex Spaniel',
	value: 'Sussex Spaniel',
	content: 'Sussex Spaniel'},
	{key: 'Teddy Roosevelt Terrier',
	text: 'Teddy Roosevelt Terrier',
	value: 'Teddy Roosevelt Terrier',
	content: 'Teddy Roosevelt Terrier'},
	{key: 'Tibetan Mastiff',
	text: 'Tibetan Mastiff',
	value: 'Tibetan Mastiff',
	content: 'Tibetan Mastiff'},
	{key: 'Toy Fox Terrier',
	text: 'Toy Fox Terrier',
	value: 'Toy Fox Terrier',
	content: 'Toy Fox Terrier'},
	{key: 'Vizsla',
	text: 'Vizsla',
	value: 'Vizsla',
	content: 'Vizsla'},
	{key: 'Weimaraner',
	text: 'Weimaraner',
	value: 'Weimaraner',
	content: 'Weimaraner'},
	{key: 'Welsh Terrier',
	text: 'Welsh Terrier',
	value: 'Welsh Terrier',
	content: 'Welsh Terrier'},
	{key: 'West Highland White Terrier',
	text: 'West Highland White Terrier',
	value: 'West Highland White Terrier',
	content: 'West Highland White Terrier'},
	{key: 'Whippet',
	text: 'Whippet',
	value: 'Whippet',
	content: 'Whippet'},
	{key: 'Xoloitzcuintli (Mexican Hairless Dog)',
	text: 'Xoloitzcuintli (Mexican Hairless Dog',
	value: 'Xoloitzcuintli (Mexican Hairless Dog',
	content: 'Xoloitzcuintli (Mexican Hairless Dog'},
	{key: 'Yorkipoo',
	text: 'Yorkipoo',
	value: 'Yorkipoo',
	content: 'Yorkipoo'},
	{key: 'Yorkshire Terrier',
	text: 'Yorkshire Terrier',
	value: 'Yorkshire Terrier',
	content: 'Yorkshire Terrier'}

]

const people = [
	{key: 'Does Not Like People',
	 text: 'Does Not Like People',
	 value: 'Does Not Like People',
	 content: 'Does Not Like People'},
	 {key: 'Shy Around People',
	 text: 'Shy Around People',
	 value: 'Shy Around People',
	 content: 'Shy Around People',},
	 {key: 'Good With People',
	 text: 'Good With People',
	 value: 'Good With People',
	 content: 'Good With People',},
	 {key: 'Loves People',
	 text: 'Loves People',
	 value: 'Loves People',
	 content: 'Loves People',}
]

const dogs = [
	{key: 'Does Not Other Like Dogs',
	 text: 'Does Not Other Like Dogs',
	 value: 'Does Not Other Like Dogs',
	 content: 'Does Not Other Like Dogs'},
	 {key: 'Shy Around Other Dogs',
	 text: 'Shy Around Other Dogs',
	 value: 'Shy Around Other Dogs',
	 content: 'Shy Around Other Dogs',},
	 {key: 'Good With Other Dogs',
	 text: 'Good With Other Dogs',
	 value: 'Good With Other Dogs',
	 content: 'Good With Other Dogs',},
	 {key: 'Loves Other Dogs',
	 text: 'Loves Other Dogs',
	 value: 'Loves Other Dogs',
	 content: 'Loves Other Dogs',}
]

const fixed = [
	{key: 'Spayed',
	 text: 'Spayed',
	 value: 'Spayed',
	 content: 'Spayed'},
	 {key: 'Neutered',
	 text: 'Neutered',
	 value: 'Neutered',
	 content: 'Neutered'},
	 {key: 'Not fixed',
	 text: 'Not fixed',
	 value: 'Not fixed',
	 content: 'Not fixed'}
]

export { breeds, people, dogs, fixed }
