const breeds = [
			{key: 'Mix',
			 text: 'Mix',
			 value: 'Mix',
			 content:'Mix'},
			{key: 'American Staffordshire Terrier',
			 text: 'American Staffordshire Terrier',
			 value: 'American Staffordshire Terrier',
			 content:'American Staffordshire Terrier'},
			{key: 'Bernese Mountain Dog',
			 text: 'Bernese Mountain Dog',
			 value: 'Bernese Mountain Dog',
			 content: 'Bernese Mountain Dog'},
			{key: 'Boxer',
			 text: 'Boxer',
			 value: 'Boxer',
			 content: 'Boxer'},
			{key: 'German Shepherd Dog',
			 text: 'German Shepherd Dog',
			 value: 'German Shepherd Dog',
			 content: 'German Shepherd Dog'},
			{key: 'Golden Retriever',
			 text: 'Golden Retriever',
			 value: 'Golden Retriever',
			 content: 'Golden Retriever'},
			 {key: 'Mini Australian Shepherd',
			 text: 'Mini Australian Shepherd',
			 value: 'Mini Australian Shepherd',
			 content: 'Mini Australian Shepherd'},
			 {key: 'Pomeranian',
			 text: 'Pomeranian',
			 value: 'Pomeranian',
			 content: 'Pomeranian'},
			 {key: 'Corgi',
			 text: 'Corgi',
			 value: 'Corgi',
			 content: 'Corgi'},
			 {key: 'Lab Mix',
			 text: 'Lab Mix',
			 value: 'Lab Mix',
			 content: 'Lab Mix'},
			 {key: 'French Bulldog',
			 text: 'French Bulldog',
			 value: 'French Bulldog',
			 content: 'French Bulldog'},
			 {key: 'Shih Tzu',
			 text: 'Shih Tzu',
			 value: 'Shih Tzu',
			 content: 'Shih Tzu'},
			 {key: 'Golden Retriever',
			 text: 'Golden Retriever',
			 value: 'Golden Retriever',
			 content: 'Golden Retriever'}
	]

const people = [
	{key: 'Does Not Like People',
	 text: 'Does Not Like People',
	 value: 'Does Not Like People',
	 content: 'Does Not Like People'},
	 {key: 'Shy Around People',
	 text: 'Shy Around People',
	 value: 'Shy Around People',
	 content: 'Shy Around People',},
	 {key: 'Good With People',
	 text: 'Good With People',
	 value: 'Good With People',
	 content: 'Good With People',},
	 {key: 'Loves People',
	 text: 'Loves People',
	 value: 'Loves People',
	 content: 'Loves People',}
]

const dogs = [
	{key: 'Does Not Other Like Dogs',
	 text: 'Does Not Other Like Dogs',
	 value: 'Does Not Other Like Dogs',
	 content: 'Does Not Other Like Dogs'},
	 {key: 'Shy Around Other Dogs',
	 text: 'Shy Around Other Dogs',
	 value: 'Shy Around Other Dogs',
	 content: 'Shy Around Other Dogs',},
	 {key: 'Good With Other Dogs',
	 text: 'Good With Other Dogs',
	 value: 'Good With Other Dogs',
	 content: 'Good With Other Dogs',},
	 {key: 'Loves Other Dogs',
	 text: 'Loves Other Dogs',
	 value: 'Loves Other Dogs',
	 content: 'Loves Other Dogs',}
]

const fixed = [
	{key: 'Spayed',
	 text: 'Spayed',
	 value: 'Spayed',
	 content: 'Spayed'},
	 {key: 'Neutered',
	 text: 'Neutered',
	 value: 'Neutered',
	 content: 'Neutered'},
	 {key: 'Not fixed',
	 text: 'Not fixed',
	 value: 'Not fixed',
	 content: 'Not fixed'}
]

export { breeds, people, dogs, fixed }
